### ISSUE TITLE
webp cache randomly not working

### ISSUE THREAD

**Issue by Notebit** [SeptdirWorkshop/jYProExtra#55] opened 2020-08-04 10:10 UTC
I am usign this plugin just for solving the webp cache problem with yootheme pro. It works but randomly I see jpeg served to Chrome or Firefox. I am not able to detect a path, but sometimes it stops serving the pages with webp and starts serving pages with jpeg to chrome or firefox.

I have the latest version of the plugin, Yootheme pro 2.0.8 and php 7.3

**Comment by Septdir** [comment] 2020-08-04 10:30
Just in case, I checked the plugin's work, and its functionality works as expected.

Your problem is most likely related to the webp generation itself and not to the plugin.

The plugin only provides storage of 2 cache files, for browsers with and without webp support.

If in the process of generating the plugin the wrong page was generated, then it will be displayed until the cache is cleared.

If the plugin did not work, then it would not work on the entire site, and not "sometimes"

**Comment by Notebit** [comment] 2020-08-04 11:02
Hi Septir,
webp generation works fine without cache.
Enabling cache and the webp cache option on youtr plugin (just the webp cache, II don't use the extended webp feature of the plugin) I can see webp in chrome and jpeg in IE at the same time, but sometimes it fails and I don't know why, and then it go back to normal again, any check I can make when I see the strange behavior?

**Comment by Septdir** [comment] 2020-08-04 11:15
When the webp cache is turned off, you can simply not notice it.

You can check.
The first thing to check is the cache selector.
To do this, you can add
```
echo '<pre>', var_dump($webP), '</pre>';
```
Before this line.  
https://github.com/SeptdirWorkshop/jYProExtra/blob/master/classes/BaseController.php#L44  
If you see true, and the site displays jpg, then the plugin worked correctly, but the page was not generated correctly.

The second is to check the files themselves
You will need to find the cache file of this page, go with ie or safari and check that there are two files and compare their contents.

Anyway, if the plugin crashed, you would rather see a page with webp on safari than a page with jpg on chome

**Comment by Notebit** [comment] 2020-08-05 06:14
OK, I will try to identify the reason. We have more than 30k articles so it means more than 30k pictures, maybe the large amount of files in yootheme/cache can be part of the problem?
After I opened this thread yesterday, I had the problem twice, yesterday night after a com_content cache refresh, and this morning, usually after some time it fixes by itself and the cache starts serving webp images to chrome and firefox, but there is some time in which it serves jpg to any browser.
Can it be useful to enable "Platform specific cache" in Joomla cache configuration?

**Comment by Septdir** [comment] 2020-08-05 11:10
The plugin works stably with this Joomla configuration
![settings](https://user-images.githubusercontent.com/18382023/89406073-42a39500-d725-11ea-97bd-6e9e1a075b5c.png)

**Comment by Notebit** [comment] 2020-08-05 12:53
OK, I just have a longer cache time of 60 minutes.
I am monitoring the situation, I saw com_content cache recaching a few times today and I don't know why, so restarting collecting cached elements.
Now I re-enabled your plugin with the webp cache option on and purged com_content cache manually. It seems to work fine so far.

There is something else I noticed but it's related to the way Yootheme Pro caches the images. First time I publish an article the picture link inside has a com_ajax link, I guess it should be just for the first time the article is generated in frontpage, and from the second time it should take the picture from yootheme/cache, but joomla cache freezes that com_ajax link for the duration of the cache time, so in my case it serves com_ajax links for the first 60 minutes

**Comment by Septdir** [comment] 2020-08-05 12:56
> There is something else I noticed but it's related to the way Yootheme Pro caches the images. First time I publish an article the picture link inside has a com_ajax link, I guess it should be just for the first time the article is generated in frontpage, and from the second time it should take the picture from yootheme/cache, but joomla cache freezes that com_ajax link for the duration of the cache time, so in my case it serves com_ajax links for the first 60 minutes

Unfortunately, there is nothing to be done about this, at least not yet.

**Comment by Notebit** [comment] 2020-08-05 15:48
going back to the main topic of this thread. now it is serving jpeg to chrome and FF again. it seems a bit unconsistant but I am not able to find a clear pattern or a cause. id doesn't happen for all the pages together, but just for some of the, others still get the webp version of the page

**Comment by Septdir** [comment] 2020-08-05 16:20
You can simply display what I threw off to you earlier.
And observe will output true or fasle
If the output is true, but there will be jpg, then this is a webp generation bug, not a plugin

**Comment by Notebit** [comment] 2020-08-05 21:54
OK, I did the var_dump check
 I get <pre>bool(true)
</pre>
in both cases, when it shows jpeg and when it shows webp

and I get bool(false) in IE

it seems I don't have any problem in IE, but I have that inconsistency in FF and Chrome, where instead of getting webp all the time, sometimes I get jpeg

**Comment by Septdir** [comment] 2020-08-05 22:16
> in both cases, when it shows jpeg and when it shows webp

In this case, the problem is not with the plugin, but with generating webp.   
So I'm closing this issue.

Regarding the problem with generating webp, I don't think it is such a big problem.  
The function of separate caching itself was created for the sake of browsers that do not support webp, so that images are displayed there when caching is enabled.  
And it is even possible that this function will be removed when safari starts to fully support webp

**Comment by Notebit** [comment] 2020-08-05 22:46
OK, I let yootheme pro generate the webp images, i don't have any custom function for that.
Can the inconsistency issue I have, depend by the fact that yootheme pro performs the webp support check in a different way compared to your plugin?
Just an idea, but is it possible that my issue depends by the fact that yootheme serves webp to a smaller amount of browsers, so there is some browser configuration for which they use jpeg but your webp check considers that browser as webp capable and adds to the cache as webp?

the webp check they use looks like this one
if (is_callable('imagewebp') && strpos($config('req.accept'), 'image/webp') !== false) {
so it looks like they do a MIME check instead of using a list of browsers versions like in your plugin

**Comment by Septdir** [comment] 2020-08-05 23:52
It's not a MIME type, it's $ _SERVER ['HTTP_ACCEPT']

I would not say that this is the best way to check for him.
But on the other hand, if we are talking about the cache, then we should probably replace it with it.

**Comment by Septdir** [comment] 2020-08-06 00:32
[plg_system_jyproextra_1.6.2-dev.zip](https://github.com/SeptdirWorkshop/jYProExtra/files/5031859/plg_system_jyproextra_1.6.2-dev.zip)
Please try this version

**Closed as completed** 2020-08-06 00:31 UTC
Labels: bug

**Comment by Septdir** [comment] 2020-08-06 10:45
@Notebit version with fix
[plg_system_jyproextra_1.6.2-dev.zip](https://github.com/SeptdirWorkshop/jYProExtra/files/5034314/plg_system_jyproextra_1.6.2-dev.zip)

**Comment by Notebit** [comment] 2020-08-06 11:28
Hi, yes i saw it, thanks, I will try to install it this evening

**Comment by Notebit** [comment] 2020-08-06 21:34
Hi, I installed it. It looks fine, I will let you know if I see any inconsistency again but for now I don't see any, thank you
